# Generated by Django 4.2.4 on 2024-06-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=80)),
                ('maths_score', models.IntegerField()),
                ('Physics_score', models.IntegerField()),
                ('Chemistry_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
